name: Test Suite

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
          
    - name: Download Dependencies
      run: |
        go mod download

    - name: Test
      run: make test
      
    - name: Lint
      run: |
        make lint-deps
        make lint
